version: '1.0.0'

services:
  nginx:
    build:
      context: ./nginx-gateway
      dockerfile: Dockerfile
    depends_on:
      - merchant-service
      #more to come here...
    ports:
      - "80:80"
    volumes:
      - ./nginx-gateway/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - naee-network

  merchant-service:
    build:
      context: ./merchant
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysql-merchant
      - DB_USER=merchant
      - DB_PASSWORD=merchant@123
      - DB_NAME=merchantDb
    depends_on:
      - merchant-mysql
    volumes:
      - ./merchant:/app
    links:
      - "merchant-mysql:mysql-merchant"
    networks:
      - naee-network

  merchant-mysql:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: merchantDb
      MYSQL_USER: merchant
      MYSQL_PASSWORD: merchant@123
    ports:
      - "3307:3306"
    volumes:
      - ./shared/databases/merchant_service_db:/var/lib/mysql
      
    command: mysqld --default-authentication-plugin=mysql_native_password
    networks:
      - naee-network

networks:
  naee-network:
    driver: bridge
